logging:
  level:
    org.springframework: info
    
spring:  jackson:    serialization:      write-dates-as-timestamps: false
        messages:    basename: message  jpa:    show-sql: true
  h2:    console:      enabled: true
    
management:  endpoints:    web:      exposure:        include:        - "*"
        